---
version: 2
defaults: &defaults
  docker:
    - image: saschagrunert/build-haskell
workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - test
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Version information
          command: |
            ghc --version
            stack --version
      - restore_cache:
          keys:
            - build-cache-{{ arch }}
      - run:
          name: Build all targets
          command: stack build
      - save_cache:
          key: build-cache-{{ arch }}
          paths:
            - .stack-work
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - test-cache-{{ arch }}
      - run:
          name: Run tests
          command: stack test --coverage
      - run:
          name: Upload coverage report
          command: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: test-cache-{{ arch }}
          paths:
            - .stack-work
